---
title: Installing Packages
subtitle: Learn how to install and import packages in R
format: live-html
engine: knitr
webr:
  packages:
    - dplyr
output: 
  learnr::tutorial:
    progressive: true
toc: true
---

{{< include ../_extensions/live/_knitr.qmd >}} ## R packages

While the base installation of R contains the core set of functions you'll use in your analyses, you may eventually come to rely on additional R packages with more specialized functionality. Since R is an open-source community with thousands of developers, R packages are constantly being developed and shared. These packages can then be installed on your local device. The most common R repository is CRAN. For most common packages you'll need, `install.packages()` will serve you well.

Try running the following code to install a common plotting package, `ggplot2`. Use single (`'`) or double (`"`) around the name of the package to install it
```{webr}
#| exercise: ex_1
____
```

## Importing packages

After installing a package, it now needs to be loaded into your workspace using the `library()` function. Try this below by replacing the underscores with code. Bear in mind that this exercise is just for demonstration. 

```{webr}
#| exercise: ex_2
____
```
